apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snmp-exporter
  namespace: argocd
spec:
  project: snmp-exporter
  source:
    repoURL: https://github.com/ryanrolds/snmp_exporter.git
    targetRevision: main
    helm:
      parameters:
        - name: ingress
          value: snmp-exporter
    path: ./chart/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: snmp-exporter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true