on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      # - name: Build source
      #   run: make common-build
      # - name: Build image
      #   run: docker build .
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.pedanticorderliness.com
          username: ${{ secrets.DOCKER_REG_USER }}
          password: ${{ secrets.DOCKER_REG_PASS }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          tags: docker.pedanticorderliness.com/snmp-exporter:${{ github.sha }}
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'chart/values.yaml'
          propertyPath: 'image.tag'
          value: '${{ github.sha }}'
          commitChange: true
          branch: main
          message: 'Update Image Version to "${{ github.sha }}' 